# Generated by Django 5.0.1 on 2024-01-21 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirQuality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('aqi', models.IntegerField()),
                ('so2', models.FloatField()),
                ('no2', models.FloatField()),
                ('pm10', models.FloatField()),
                ('pm25', models.FloatField()),
                ('o3', models.FloatField()),
                ('co', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CityWeather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=255)),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('wind_speed', models.FloatField()),
            ],
        ),
    ]
